server:
  port: 7001

#eureka配置
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/  #单机
#     defaultZone: http://eureka7002.com:7002/eureka/   #集群
